export const GENRE_COLORS: Record<string, string> = {
  Action: 'red',
  Drama: 'blue',
  Comedy: 'gold',
  Thriller: 'purple',
  'Sci-Fi': 'cyan',
  Horror: 'volcano',
  Romance: 'pink',
  Animation: 'green',
  Crime: 'volcano',
  Mystery: 'purple',
  Documentary: 'green',
  Family: 'lime',
  'Science Fiction': 'cyan',
  'Sci-Fi & Fantasy': 'cyan',
  'Action & Adventure': 'red',
  'TV Movie': 'geekblue',
  Kids: 'lime',
  News: 'geekblue',
  Reality: 'orange',
  Soap: 'magenta',
  Talk: 'purple',
  'War & Politics': 'volcano',
  History: 'orange',
  Music: 'purple',
  War: 'red',
  Western: 'gold',
  Fantasy: 'magenta',
  Adventure: 'blue',
};
